CREATE TABLE TBL_PLAYER (
    NAME VARCHAR2(50),
    VICTORIES NUMBER(5) DEFAULT 0,
    EMPATES NUMBER(5) DEFAULT 0,
    DEFEATS NUMBER(5) DEFAULT 0,
    CONSTRAINT PK_PLAYER PRIMARY KEY (NAME)
);

CREATE TABLE TBL_INITIAL_POSITIONS(
    CODE NUMBER(3),
    COORDINATE_X NUMBER(5) NOT NULL,
    COORDINATE_Y NUMBER(5) NOT NULL
    CONSTRAINT PK_INITIAL_POSITIONS PRIMARY KEY (CODE)
);

CREATE TABLE TBL_CHESS_PIECES(
    CODE NUMBER(3),
    NAME_PIECE VARCHAR2(50) NOT NULL,
    COLOR VARCHAR2(50) NOT NULL,
    INITIALS VARCHAR2(50) NOT NULL,
    ID_INITIAL_POSITION NUMBER(3),
    CONSTRAINT PK_CHESS_PIECES PRIMARY KEY (CODE),
    CONSTRAINT FK_INITIAL_POSITIONS_IN_CP FOREIGN KEY (ID_INITIAL_POSITION) REFERENCES TBL_INITIAL_POSITIONS (CODE)
);

CREATE TABLE TBL_GAME(
    CODE NUMBER(3),
    START_DATE DATE NOT NULL,
    ENDING_DATE DATE NOT NULL,
    CONSTRAINT PK_GAME PRIMARY KEY (CODE)
);

CREATE TABLE TBL_PLAYER_BY_GAMES(
    ID_PLAYER_1 VARCHAR2(50),
    ID_PLAYER_2 VARCHAR2(50),
    ID_GAME NUMBER(3),
    GAME_STATUS VARCHAR2(1) NOT NULL,
    CONSTRAINT FK_PLAYER_1_IN_PG FOREIGN KEY (ID_PLAYER_1) REFERENCES TBL_PLAYER(NAME),
    CONSTRAINT FK_PLAYER_2_IN_PG FOREIGN KEY (ID_PLAYER_2) REFERENCES TBL_PLAYER(NAME),
    CONSTRAINT FK_GAME_IN_PG FOREIGN KEY (ID_GAME) REFERENCES TBL_GAME(CODE)
);

CREATE TABLE TBL_CHESS_PIECES_BY_GAMES(
    CODE NUMBER(3),
    CHESS_PIECES_STATUS VARCHAR2(1) NOT NULL, 
    ORIGIN_COORDINATE_X NUMBER(5) NOT NULL,
    ORIGIN_COORDINATE_Y NUMBER(5) NOT NULL,
    DESTINATION_COORDINATE_X NUMBER(5) NOT NULL,
    DESTINATION_COORDINATE_Y NUMBER(5) NOT NULL,
    ID_CHESS_PIECE NUMBER(3),
    ID_GAME NUMBER(3),
    CONSTRAINT PK_CHESS_PIECES_BY_GAMES PRIMARY KEY (CODE),
    CONSTRAINT FK_CHESS_PIECE_IN_CPG FOREIGN KEY (ID_CHESS_PIECE) REFERENCES TBL_CHESS_PIECES(CODE),
    CONSTRAINT FK_GAME_IN_CPG FOREIGN KEY (ID_GAME) REFERENCES TBL_ GAME(CODE)
);

CREATE SEQUENCE PRIMARY_CHESS_PIECES
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE PRIMARY_GAME
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE PRIMARY_MOVES
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE PRIMARY_CHESS_PIECES_BY_GAMES
START WITH 1
INCREMENT BY 1;