--Piezas

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Rey', 'Blanco', 'R', 4);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Dama', 'Blanco', 'D', 5);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Torre', 'Blanco', 'T', 1);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Torre', 'Blanco', 'T', 8);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Alfil', 'Blanco', 'A', 3);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Alfil', 'Blanco', 'A', 6);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Caballo', 'Blanco', 'C', 2);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Caballo', 'Blanco', 'C', 7);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Peon', 'Blanco', 'P', 9);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Peon', 'Blanco', 'P', 10);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Peon', 'Blanco', 'P', 11);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Peon', 'Blanco', 'P', 12);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Peon', 'Blanco', 'P', 13);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Peon', 'Blanco', 'P', 14);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Peon', 'Blanco', 'P', 15);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Peon', 'Blanco', 'P', 16);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Rey', 'Negro', 'r', 20);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Dama', 'Negro', 'd', 21);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Torre', 'Negro', 't', 17);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Torre', 'Negro', 't', 24);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Alfil', 'Negro', 'a', 19);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Alfil', 'Negro', 'a', 23);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Caballo', 'Negro', 'c', 18);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Caballo', 'Negro', 'c', 22);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Peon', 'Negro', 'p', 25);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Peon', 'Negro', 'p', 26);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Peon', 'Negro', 'p', 27);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Peon', 'Negro', 'p', 28);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Peon', 'Negro', 'p', 29);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Peon', 'Negro', 'p', 30);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Peon', 'Negro', 'p', 31);

INSERT INTO TBL_CHESS_PIECES (CODE, NAME_PIECE, COLOR, INITIALS, ID_INITIAL_POSITION) 
VALUES (PRIMARY_CHESS_PIECES.NEXTVAL, 'Peon', 'Negro', 'p', 32);