    INSERT INTO TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y)
VALUES (1, 1, 1); 
--Torre blanco 1.

INSERT INTO TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y)
VALUES (2, 2, 1); 
--Caballo blanco 1.

INSERT INTO TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y)
VALUES (3, 3, 1);
--Alfin blanco 1.

INSERT INTO TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y)
VALUES (4, 4, 1);
--Rey blanco.

INSERT INTO TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y)
VALUES (5, 5, 1);
--Dama blanca.

INSERT INTO TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y)
VALUES (6, 6, 1); 
--Alfin blanco 2.

INSERT INTO TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y)
VALUES (7, 7, 1); 
--Caballo blanco 2.

INSERT INTO TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y)
VALUES (8, 8, 1); 
--Torre blanco 2.

INSERT INTO TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y)
VALUES (9, 1, 2); 
--Peon blanco 1.

INSERT INTO TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y)
VALUES (10, 2, 2); 
--Peon blanco 2.

INSERT INTO TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y)
VALUES (11, 3, 2); 
--Peon blanco 3.

INSERT INTO  TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y)
VALUES (12, 4, 2); 
--Peon blanco 4.

INSERT INTO  TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y )
VALUES (13, 5, 2); 
--Peon blanco 5.

INSERT INTO  TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y )
VALUES (14, 6, 2); 
--Peon blanco 6.

INSERT INTO  TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y )
VALUES (15, 7, 2); 
--Peon blanco 7.

INSERT INTO  TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y )
VALUES (16, 8, 2); 
--Peon blanco 8.

INSERT INTO  TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y )
VALUES (17, 1, 8); 
--Torre negro 1.

INSERT INTO  TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y )
VALUES (18, 2, 8); 
--Caballo negro 1.

INSERT INTO  TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y )
VALUES (19, 3, 8); 
--Alfin negro 1.

INSERT INTO  TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y )
VALUES (20, 4, 8); 
--Rey negro.

INSERT INTO  TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y )
VALUES (21, 5, 8); 
--Dama negro.

INSERT INTO  TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y )
VALUES (22, 6, 8); 
--Alfin negro 2.

INSERT INTO  TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y )
VALUES (23, 7, 8);
 --Caballo negro 2.

INSERT INTO  TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y )
VALUES (24, 8, 8); 
--Torre negro 2.

INSERT INTO  TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y )
VALUES (25, 1, 7); 
--Peon negro 1.

INSERT INTO  TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y )
VALUES (26, 2, 7); 
--Peon negro 2.

INSERT INTO  TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y )
VALUES (27, 3, 7); 
--Peon negro 3.

INSERT INTO  TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y )
VALUES (28, 4, 7); 
--Peon negro 4.

INSERT INTO  TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y )
VALUES (29, 5, 7); 
--Peon negro 5.

INSERT INTO  TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y )
VALUES (30, 6, 7); 
--Peon negro 6.

INSERT INTO  TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y )
VALUES (31, 7, 7); 
--Peon negro 7.

INSERT INTO  TBL_INITIAL_POSITIONS (CODE, COORDINATE_X, COORDINATE_Y )
VALUES (32, 8, 7); 
--Peon negro 8.
/