CREATE OR REPLACE PROCEDURE PR_CREATE_GAME(P_START_DATE DATE) IS
BEGIN
    INSERT INTO TBL_GAME (CODE, START_DATE, ENDING_DATE)
    VALUES (PRIMARY_GAME.NEXTVAL, P_START_DATE, P_START_DATE);
END;
/