CREATE OR REPLACE PROCEDURE PR_INITIAL_POSITIONS(REGISTROS OUT SYS_REFCURSOR) AS
BEGIN
    OPEN REGISTROS FOR SELECT C.INITIALS, I.COORDINATE_X, I.COORDINATE_Y FROM TBL_CHESS_PIECES C INNER JOIN TBL_INITIAL_POSITIONS I
                        ON C.ID_INITIAL_POSITION = I.CODE;
END;
/