CREATE OR REPLACE PROCEDURE PR_SAVE_GAME(P_ID_PLAYER_1 VARCHAR2, P_ID_PLAYER_2 VARCHAR2) AS
    ID_GAME NUMBER(5, 0);
    CURSOR cChess_Pieces IS SELECT CP.CODE, P.COORDINATE_X, P.COORDINATE_Y FROM TBL_CHESS_PIECES CP 
                            INNER JOIN TBL_INITIAL_POSITIONS P ON CP.ID_INITIAL_POSITION = P.CODE;
BEGIN
    ID_GAME := PRIMARY_GAME.NEXTVAL;
    INSERT INTO TBL_GAME(CODE, START_DATE, ENDING_DATE)
    VALUES(ID_GAME, sysdate, sysdate);

    FOR PieceGame IN cChess_Pieces LOOP
        INSERT INTO TBL_CHESS_PIECES_BY_GAMES (CODE, CHESS_PIECES_STATUS, ORIGIN_COORDINATE_X, ORIGIN_COORDINATE_Y,
        DESTINATION_COORDINATE_X, DESTINATION_COORDINATE_Y, ID_CHESS_PIECE, ID_GAME)
        VALUES (PRIMARY_CHESS_PIECES_BY_GAMES.NEXTVAL, 'A', PieceGame.COORDINATE_X, PieceGame.COORDINATE_Y, 0, 0, PieceGame.CODE, ID_GAME);
    END LOOP;

    INSERT INTO TBL_PLAYER_BY_GAMES (ID_PLAYER_1, ID_PLAYER_2, ID_GAME, GAME_STATUS)
    VALUES(P_ID_PLAYER_1, P_ID_PLAYER_2, ID_GAME, 'A');
END;
/