CREATE OR REPLACE FUNCTION PR_GET_COLOR_CHESS_PIECE(P_FINAL_X NUMBER, P_FINAL_Y NUMBER, P_ID_GAME NUMBER) RETURN VARCHAR2
IS
    Color_Chess_Piece VARCHAR2(50);
BEGIN
    SELECT C.COLOR INTO Color_Chess_Piece FROM TBL_CHESS_PIECES_BY_GAMES CP INNER JOIN TBL_CHESS_PIECES C
    ON CP.ID_CHESS_PIECE = C.CODE WHERE CP.ORIGIN_COORDINATE_X = P_FINAL_X AND CP.ORIGIN_COORDINATE_Y = P_FINAL_Y
    AND CP.ID_GAME = P_ID_GAME;
    RETURN Color_Chess_Piece;
EXCEPTION 
    WHEN NO_DATA_FOUND THEN
        Color_Chess_Piece := 'Libre';
        RETURN Color_Chess_Piece;
END;
/