CREATE OR REPLACE FUNCTION PR_VALIDATE_MOVE_CABALLO(P_ORIGIN_X NUMBER, P_ORIGIN_Y NUMBER, P_FINAL_X NUMBER, P_FINAL_Y NUMBER)
RETURN VARCHAR2
IS
    URX NUMBER(2) := P_ORIGIN_X + 1;
    URY NUMBER(2) := P_ORIGIN_Y + 2;
    ULX NUMBER(2) := P_ORIGIN_X - 1;
    ULY NUMBER(2) := P_ORIGIN_Y + 2;
    DRX NUMBER(2) := P_ORIGIN_X + 1;
    DRY NUMBER(2) := P_ORIGIN_Y - 2;
    DLX NUMBER(2) := P_ORIGIN_X - 1;
    DLY NUMBER(2) := P_ORIGIN_Y - 2;
    LUX NUMBER(2) := P_ORIGIN_X - 2;
    LUY NUMBER(2) := P_ORIGIN_Y + 1;
    LDX NUMBER(2) := P_ORIGIN_X - 2;
    LDY NUMBER(2) := P_ORIGIN_Y - 1;
    RUX NUMBER(2) := P_ORIGIN_X + 2;
    RUY NUMBER(2) := P_ORIGIN_Y + 1;
    RDX NUMBER(2) := P_ORIGIN_X + 2;
    RDY NUMBER(2) := P_ORIGIN_Y - 1;
BEGIN
    IF(P_FINAL_X = URX AND P_FINAL_Y = URY) THEN
        RETURN 'TRUE';
    END IF;

    IF(P_FINAL_X = ULX AND P_FINAL_Y = ULY) THEN
        RETURN 'TRUE';
    END IF;

    IF(P_FINAL_X = DLX AND P_FINAL_Y = DLY) THEN
        RETURN 'TRUE';
    END IF;

    IF(P_FINAL_X = DRX AND P_FINAL_Y = DRY) THEN
        RETURN 'TRUE';
    END IF;

    IF(P_FINAL_X = LUX AND P_FINAL_Y = LUY) THEN
        RETURN 'TRUE';
    END IF;

    IF(P_FINAL_X = LDX AND P_FINAL_Y = LDY) THEN
        RETURN 'TRUE';
    END IF;

    IF(P_FINAL_X = RUX AND P_FINAL_Y = RUY) THEN
        RETURN 'TRUE';
    END IF;

    IF(P_FINAL_X = RDX AND P_FINAL_Y = RDY) THEN
        RETURN 'TRUE';
    END IF;

    RETURN 'FALSE';
END;
/